config/routes.rb
Rails.application.routes.draw do
  resources :mymemos

end

app/models/mymemo.rb
class Mymemo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mymemos_controller.rb
class MymemosController < ApplicationController
  before_action :set_mymemo, only: [:show, :edit, :update, :destroy]

  # GET /mymemos
  # GET /mymemos.json
  def index
    @mymemos = Mymemo.all
  end

  # GET /mymemos/1
  # GET /mymemos/1.json
  def show
  end

  # GET /mymemos/new
  def new
    @mymemo = Mymemo.new
  end

  # GET /mymemos/1/edit
  def edit
  end

  # POST /mymemos
  # POST /mymemos.json
  def create
    @mymemo = Mymemo.new(mymemo_params)

    respond_to do |format|
      if @mymemo.save
        format.html { redirect_to @mymemo, notice: 'Mymemo was successfully created.' }
        format.json { render :show, status: :created, location: @mymemo }
      else
        format.html { render :new }
        format.json { render json: @mymemo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mymemos/1
  # PATCH/PUT /mymemos/1.json
  def update
    respond_to do |format|
      if @mymemo.update(mymemo_params)
        format.html { redirect_to @mymemo, notice: 'Mymemo was successfully updated.' }
        format.json { render :show, status: :ok, location: @mymemo }
      else
        format.html { render :edit }
        format.json { render json: @mymemo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mymemos/1
  # DELETE /mymemos/1.json
  def destroy
    @mymemo.destroy
    respond_to do |format|
      format.html { redirect_to mymemos_url, notice: 'Mymemo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mymemo
      @mymemo = Mymemo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mymemo_params
      params.require(:mymemo).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mymemos_helper.rb
module MymemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mymemoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mymemos/_form.html.erb
<%= form_for(@mymemo) do |f| %>
  <% if @mymemo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mymemo.errors.count, "error") %> prohibited this mymemo from being saved:</h2>

      <ul>
      <% @mymemo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mymemos/edit.html.erb
<h1>Editing Mymemo</h1>

<%= render 'form' %>

<%= link_to 'Show', @mymemo %> |
<%= link_to 'Back', mymemos_path %>

app/views/mymemos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mymemos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mymemos.each do |mymemo| %>
      <tr>
        <td><%= mymemo.title %></td>
        <td><%= mymemo.body %></td>
        <td><%= link_to 'Show', mymemo %></td>
        <td><%= link_to 'Edit', edit_mymemo_path(mymemo) %></td>
        <td><%= link_to 'Destroy', mymemo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mymemo', new_mymemo_path %>

app/views/mymemos/new.html.erb
<h1>New Mymemo</h1>

<%= render 'form' %>

<%= link_to 'Back', mymemos_path %>

app/views/mymemos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mymemo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @mymemo.body %>
</p>

<%= link_to 'Edit', edit_mymemo_path(@mymemo) %> |
<%= link_to 'Back', mymemos_path %>